# Generated by Django 5.1 on 2025-09-03 07:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('compounding', models.CharField(choices=[('SIMPLE', 'Simple'), ('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], max_length=10)),
                ('currency', models.CharField(choices=[('AUD', 'AUD'), ('GBP', 'GBP')], max_length=3)),
                ('fx_aud_to_gbp', models.DecimalField(decimal_places=6, default=Decimal('0.520000'), max_digits=12)),
                ('fx_gbp_to_aud', models.DecimalField(decimal_places=6, default=Decimal('1.923077'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(choices=[('AUD', 'AUD'), ('GBP', 'GBP')], max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('AU', 'Australia'), ('GB', 'United Kingdom')], default='AU', max_length=2)),
                ('marginal_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_year_start_month', models.IntegerField(default=7)),
                ('tax_year_start_day', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
