# Generated by Django 5.1 on 2025-09-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxprofile',
            name='tax_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='taxprofile',
            name='tax_threshold_currency',
            field=models.CharField(default='AUD', max_length=3),
        ),
    ]
