# Generated by Django 5.1 on 2025-09-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_taxprofile_tax_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pension',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pension',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
