# Generated by Django 5.1 on 2025-09-05 01:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_alter_pension_end_date_alter_pension_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pension',
            name='tax_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
